name: Project Test

on:
  pull_request:
    branches:
    - master
    - develop

jobs:
  test:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Phidget
        run: |
          curl -fsSL https://www.phidgets.com/downloads/setup_linux | sudo -E bash - &&\
          sudo apt-get install -y libphidget22

      - name: Install MRPT
        run: |
          sudo add-apt-repository ppa:joseluisblancoc/mrpt
          sudo apt install libmrpt-dev mrpt-apps
          sudo apt install python3-pymrpt

      - name: Install project dev requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      
      - name: Run project tests
        run: python -m pytest tests/ --cov